version: '3.9'

services:
  mysql_server:
    container_name: mysql
    image: mysql:${MYSQL_TAG}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: public
      MYSQL_DATABASE: mqtt
      MYSQL_USER: ssluser
      MYSQL_PASSWORD: public
    ports:
      - 3306:3306
    volumes:
      - ./certs/cert/ca.pem:/etc/certs/ca-cert.pem
      - ./certs/cert/emqx.pem:/etc/certs/server-cert.pem
      - ./certs/cert/emqx.key:/etc/certs/server-key.pem
    networks:
      - emqx_bridge
    command:
      --bind-address "::"
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --skip-symbolic-links
      --ssl-ca=/etc/certs/ca-cert.pem
      --ssl-cert=/etc/certs/server-cert.pem
      --ssl-key=/etc/certs/server-key.pem