version: '3.9'

services:
  emqx_single_server2:
    container_name: emqx_single2
    image: $TARGET:$EMQX_TAG
    networks:
      - emqx_bridge
networks:
  emqx_bridge:
    driver: bridge
    name: emqx_bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.239.0/24
          gateway: 172.100.239.1
